services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=pizzashop
    volumes:
      - pg_pizzashop_data:/bitnami/postgresql

volumes:
  pg_pizzashop_data:
